### ISSUE TITLE
Battery / Plugged - status is not being updated during game

### ISSUE THREAD

**Issue by yodamaster726** [Alistair-Crompton/DGTCentaurMods#16]
For a few builds now, the battery status is not being updated.  When I plugin my board it doesn't update the status either to charging.

Latest tested:  https://github.com/Alistair-Crompton/DGTCentaurMods/releases/tag/ON23091002

**Comment by yodamaster726** [comment]
Two things were discovered.  
1.  Adapter and cable being used, didn't provide the right level of power.
2. When using hte right adapter and cable, the status is only updated if the board is on the menus.  Once the game has started / playing, the battery indicator is not updated.
@Alistair-Crompton

**Comment by Alistair-Crompton** [comment]
The battery icon is now updated during games.
