### ISSUE TITLE
Display time in local time zone format

### ISSUE THREAD

**Issue by yodamaster726** [Alistair-Crompton/DGTCentaurMods#18]
Minor, would be nice if the time could be displayed in local time format.   Maybe a setting ?  
ie.  12:45pm or 10:25am.

**Comment by Alistair-Crompton** [comment]
I've just added a dedicated configuration key that handles the clock format.

Following conf will display as you mentionned.
(you have to restart the core service to reload your changes)

[system]
clock_format = %%I:%%-M%%p
