### ISSUE TITLE
Game freezes if left idle for a while even if plugged in

### ISSUE THREAD

**Issue by yodamaster726** [Alistair-Crompton/DGTCentaurMods#20]
Game freezes / board goes to sleep or something if left without any activity for like 10-15 min, not sure exactly what time.  
None of the buttons are active and I also get kicked out off the network.   If I hold down the play/power button for like 15 sec, I get the power beep and then when I press the play/power it starts the circles and then I can resume the game.
This has happened to me several times.  

Before, if I had the power plugged in the board would never go to sleep.  and if it was unplugged, if it did go to sleep, the screen would change to the power down screen.  It looks like we don't have the power management working anymore.

Here are my two logs.  I was 3 moves into the game

<img width="1184" alt="image" src="https://github.com/Alistair-Crompton/DGTCentaurMods/assets/106496194/9adeba9b-3f64-443f-8a5a-d150bf87f616">

<img width="1136" alt="image" src="https://github.com/Alistair-Crompton/DGTCentaurMods/assets/106496194/cc203565-9d1f-4755-9180-e69139d1b16c">

<img width="1341" alt="image" src="https://github.com/Alistair-Crompton/DGTCentaurMods/assets/106496194/19ca3fca-778d-496b-ad78-d217d4a85c88">

**Comment by Alistair-Crompton** [comment]
I guess this old issue is now resolved.
