### ISSUE TITLE
need a way to resign a game

### ISSUE THREAD

**Issue by djaramil** [Alistair-Crompton/DGTCentaurMods#26]
when playing a game, there is no way to resign and start a new game easily

**Comment by Alistair-Crompton** [comment]
When you place your pieces back in starting position, you start a new game, that's a good quick way to resign or start a new game isn't it?
When you play on Lichess, you can push the tick button: a Centaur window pops up and offers you to resign.

**Comment by djaramil** [comment]
I guess - I was hoping that it would be like you said with Lichess - that to me seems the more intuitive way.
If you don't agree, I'll close this issue.

**Comment by Alistair-Crompton** [comment]
The resign window already exists (and had anyway to be refactored),
we only need to make the resignation process generic, optionally and
defaultly handled by the Game Factory.

I will affect the UP key to the resignation (Lichess was using the TICK key
but the key is already taken by the live evaluation).


Le jeu. 28 sept. 2023 à 17:48, David Jaramillo ***@***.***> a
écrit :
