### ISSUE TITLE
socket connection fails and DGTMods doesn't startup 

### ISSUE THREAD

**Issue by djaramil** [Alistair-Crompton/DGTCentaurMods#48]
@Alistair, I'm traveling at the moment with my board - don't know if this is some coincidence, but my board fails to startup.  I have a separate wifi hub that I use to keep the ssid the same, etc.  I know the board is connecting because I take out the piw and I'm able to boot and connect.  However, when it is in the board, it doesn't complete the startup.   I looked at the logs, and there is an error where the code fails to connect to the websocket server.

Last time I coconnected was back on 5/18
[2024-05-18 22:17:24] [DGTCentaurMods] [DEBUG] -> Connecting to https://alistair-centaur-mods-nodejs.adaptable.app/...

Looks like your adaptable server has stopped or has been removed ?  and the code maybe left in a bad state.
Do we have a way of disabling the websocket code ?

[2024-05-27 14:17:12] [DGTCentaurMods] [INFO] Logging started.
[2024-05-27 14:17:12] [DGTCentaurMods] [DEBUG] -> Connecting to http://localhost...
[2024-05-27 14:17:12] [DGTCentaurMods] [ERROR] __init__ -> Unable to connect to SOCKETIO SERVER!
Traceback (most recent call last):
  File "/opt/DGTCentaurMods/classes/SocketClient.py", line 57, in initialize
    sio.connect(uri)
  File "/home/pi/.local/lib/python3.9/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with 
url: /socket.io/?transport=polling&EIO=4&t=1716833832.7482934 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75561f28>: 
Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-05-27 14:17:14] [DGTCentaurMods] [INFO] Logging started.
[2024-05-27 14:17:14] [DGTCentaurMods] [DEBUG] -> Starting socketio server...
[2024-05-27 14:17:25] [DGTCentaurMods] [ERROR] _initialize -> No response from serial!
NoneType: None
[2024-05-27 14:17:25] [DGTCentaurMods] [INFO] Board communication has been disabled...
[2024-05-27 14:17:27] [DGTCentaurMods] [INFO] board idle_time=30mn.
[2024-05-27 14:17:27] [DGTCentaurMods] [DEBUG] -> Connecting to http://localhost...
[2024-05-27 14:17:27] [DGTCentaurMods] [INFO] Starting DGTCentaurMods service...
[2024-05-27 14:17:28] [DGTCentaurMods] [INFO] Service DGTCentaurMods up and running.

**Comment by Alistair-Crompton** [comment]
Hey David, I sometimes have the same issue: the adaptable server becomes unreachable.
In that case, I end up to connect the server after restarting the WEB services (doing that from the web interface is ok).
I think the adaptable server might sometimes need to wake up (it's a free hosting plan).
I would need to migrate the server to a real server, I never did that since I'm not sure about the people that use the "connected" plugins.

**Comment by djaramil** [comment]
Yea, I agree about the adaptable server - I have one and I remember seeing an email fly by on that.

Do you think the code is in a bad state when it can't reach the server ? hence the error after:
[2024-05-27 14:17:25] [DGTCentaurMods] [ERROR] _initialize -> No response from serial!
NoneType: None

Will you be restarting the server and I can check to see if that fixes the issue ?  Or is there a way to turn off that module ?

**Comment by Alistair-Crompton** [comment]
When I'm talking about restarting the web services I'm talking about about the WEB CENTAUR MOD services, not the the adaptable services ones.

**Comment by djaramil** [comment]
I will give that a try and see if I can connect from web browser to restart because I'm not able to connect via ssh to restart.
When the circles are running on the board, it seems like it locks out the network requests or the starting of sshd ... not sure.

**Comment by djaramil** [comment]
I reinstalled everything on a new SD card and things are running now.

**Comment by djaramil** [comment]
This is strange.  The board ran once, but then when I restarted it the next day, the circles just keep on looping.   
Again, I looked at the log and it is failing in connecting with the socker server. 

<img width="985" alt="image" src="https://github.com/Alistair-Crompton/DGTCentaurMods/assets/6727195/1edce1ea-a1f1-4fe6-a2e5-9a2fcc57be92">

However, I looked a little closer and the strange thing, the exception is saying that it is trying to connect to http://localhost... - look like the uri is not being passed in.  shouldn't this have the adaptable server address ?

<img width="699" alt="image" src="https://github.com/Alistair-Crompton/DGTCentaurMods/assets/6727195/9e8404d6-4532-4dac-9efe-d4b044094692">

Appreciate any help or direction on this.

**Comment by djaramil** [comment]
After uninstalling and reinstalling various versions, trying to figure out the connecting error, I wound up installing the latest version again, manually had to start the DGTCentaurModsWeb service - which is what I think it was trying to connect to the whole time.

I'm good for now.  I'm not going to power down my board until I'm leaving and try again from back home.
Thanks for the help.
