### ISSUE TITLE
Install procedure

### ISSUE THREAD

**Issue by Leszek1975** [Alistair-Crompton/DGTCentaurMods#51]
Hello, my name is Leszek, I have a DGT centaur chess computer and I am interested in the modification, I already have a Raspberry Pi 2w board and a 32 GB SD card.
the problem is that the installation method is not understandable to me, please explain it step by step.
Install procedure

    From your Pi, download the latest available release:

wget -O ./_DGTCentaurMods_A.alpha-latest.deb `curl -s https://api.github.com/repos/Alistair-Crompton/DGTCentaurMods/releases/latest | grep browser_download_url | cut -d '"' -f 4`

    Install the downloaded package:

sudo apt install -y ./_DGTCentaurMods_A.alpha-latest.deb

    Reboot:

sudo reboot
Thank you and best regards

**Comment by Alistair-Crompton** [comment]
Hey Leszek, welcome,
please don't use this issues thread to ask about the installation procedure, definitely not the right place.
Please go to the support thread from the Discord channel.
Thanks

**Comment by Leszek1975** [comment]
OK, I already raised this issue on discord a few months ago, but Mr. ED Nekebno will simply delete this post, claiming that his ideas for modifying DGT centaur were stolen by the alistar website. That&#39;s why I decided to write directly to alistar, if you can help me, thank you very much. Regards   
     
      
       
        Dnia 22 listopada 2024 14:57 Alistair Crompton ***@***.***&gt; napisał(a):
       
    
       
         
 Hey Leszek, welcome,  
please don&#39;t use this issues thread to ask about the installation procedure, definitely not the right place.  
Please go to the support thread from the Discord channel.  
Thanks
